name: CI on Ubuntu

on:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-20.04
        - ubuntu-latest
        ruby:
        - 3.0
        - 2.7
        - 2.6
        - 2.5
        - 2.4
        - 2.3
        - debug

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Install requirements on ubuntu
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends \
                 libczmq-dev \
                 python3 \
                 python3-pip \
                 python3-setuptools
        sudo pip3 install wheel
        sudo pip3 install -r ci/requirements.txt

    - run: bundle install --jobs 4 --retry 3

    - name: Run tests
      env:
        PYTHON: python3
        ADAPTERS: cztop ffi-rzmq pyzmq
      run: |
        for adapter in $ADAPTERS; do
          export IRUBY_TEST_SESSION_ADAPTER_NAME=$adapter
          bundle exec rake test TESTOPTS=-v
        done

    - run: rake build

    - run: gem install pkg/*.gem
