name: CI on Windows

on:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - windows-latest
        ruby:
        - "3.0"
        - 2.7
        - 2.6
        - 2.5
        - 2.4
        - 2.3
        - mswin
        - mingw

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - uses: actions/cache@v2
      with:
        path: C:\vcpkg\downloads
        key: ${{ runner.os }}-vcpkg-downloads-${{ matrix.os }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-downloads-${{ matrix.os }}-
          ${{ runner.os }}-vcpkg-downloads-

    - name: Install requirements on vcpkg
      run: |
        vcpkg --triplet x64-windows install zeromq czmq libffi
        dir C:/vcpkg/installed/x64-windows/bin
        cp C:/vcpkg/installed/x64-windows/bin/libzmq-mt-4_3_3.dll C:/vcpkg/installed/x64-windows/bin/libzmq.dll

    - name: Add vcpkg bindir in PATH
      run: echo "C:/vcpkg/installed/x64-windows/bin" >> $GITHUB_PATH
      shell: bash

    - run: pip3 install -r ci/requirements.txt

    - run: bundle install --jobs 4 --retry 3 --without "pycall cztop"

    - name: Run test with ffi-rzmq
      run: bundle exec rake test TESTOPTS=-v
      env:
        IRUBY_TEST_SESSION_ADAPTER_NAME: ffi-rzmq

    - run: rake build

    - run: gem install pkg/*.gem
